In [2]:
import numpy as np
print(np)

<module 'numpy' from '/usr/local/anaconda3/lib/python3.8/site-packages/numpy/__init__.py'>


In [3]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [6]:
# 1. How many negative numbers are there?
# 4 negative numbers
len(a[a < 0])

4

In [8]:
# 2. How many positive numbers are there?
# 5 negative numbers
len(a[a > 0])

5

In [51]:
# 3. How many even positive numbers are there?
# 

#(a([a >0])) and (a[a % 2 == 0])

In [97]:
a[a % 2 == 0], a[a > 0]

(array([ 4, 10, 12, -2,  0,  0,  0, -6]), array([ 4, 10, 12, 23,  3]))

In [100]:
# 4. If you were to add 3 to each data point,
# how many positive numbers would there be?
# 10 positive numbers
original_array = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
new4 = original_array + 3

In [101]:
original_array = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
original_array + 3

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [137]:
# 5. If you squared each number, 
# what would the new mean and standard deviation be?

import math as math
original_array = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
new_array = original_array **2
print(new_array)

[ 16 100 144 529   4   1   0   0   0  36   9  49]


In [138]:
# mean of OG numbers
mean = np.mean(a)
print(mean)

3.0


In [139]:
# standard deviation of OG numbers
std = np.std(a)
print(std)

8.06225774829855


In [136]:
# mean of numbers new
meannew = np.mean(new_array)
print(mean)

74.0


In [135]:
# standard deviation of new
stdnew = np.std(new_array)
print(std)

144.0243035046516


In [87]:
# 6. A common statistical operation on a dataset is centering. 
# This means to adjust the data such that the mean of the data is 0. 
# This is done by subtracting the mean from each data point. 
# Center the data set. See this link for more on centering.
#std numbers:
centering_array = [16, 100, 144, 529, 4, 1, 0, 0, 0, 36, 9, 49]
centering_new_array = new_array - mean
print(centering_new_array)

[-58.  26.  70. 455. -70. -73. -74. -74. -74. -38. -65. -25.]


In [103]:
#original numbers
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
centering_new_array6 = a - mean7
print(centering_new_array6)

[  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.]


In [125]:
# 7. Calculate the z-score for each data point. 
# Recall that the z-score is given by:
#original values

a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])


In [130]:
zscore7 = (a - mean) / std
zscore7

array([-0.48602908, -0.44436945, -0.4304829 , -0.3541069 , -0.52768872,
       -0.52074544, -0.51380217, -0.51380217, -0.51380217, -0.55546181,
       -0.49297235, -0.56240508])

In [142]:
#Squared values z score

zscore5 = (new_array - meannew / stdnew )
zscore5

array([ 1.54861978e+01,  9.94861978e+01,  1.43486198e+02,  5.28486198e+02,
        3.48619783e+00,  4.86197828e-01, -5.13802172e-01, -5.13802172e-01,
       -5.13802172e-01,  3.54861978e+01,  8.48619783e+00,  4.84861978e+01])

# More NumPy 

In [172]:
import numpy as np
# Life w/o numpy to life with numpy

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of 
# all the numbers in above list

sum_of_a = np.sum(a)
sum_of_a

55

In [167]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of 
# all the numbers in the above list

min_of_a = np.min(a)
min_of_a


1

In [166]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of
# all the numbers in the above list

max_of_a = np.max(a)
max_of_a

10

In [165]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of 
# all the numbers in the above list

mean_of_a = np.mean(a)
mean_of_a

5.5

In [173]:
# Exercise 5 - Make a variable named product_of_a to hold the product 
# of multiplying all the numbers in the above list together

product_of_a = np.prod(a)
product_of_a

3628800

In [176]:
# Exercise 6 - Make a variable named squares_of_a.It should hold each 
# number in a squared like [1, 4, 9, 16, 25...]

squares_of_a = np.square(a)
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [190]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only 
# the odd numbers

odds_in_a = [n for n in a if n % 2 == 1]
odds_in_a

[1, 3, 5, 7, 9]

In [ ]:
# Exercise 8 - Make a variable named evens_in_a. 
#It should hold only the evens.

In [191]:
evens_in_a = [n for n in a if n % 2 == 0]
evens_in_a

[2, 4, 6, 8, 10]

In [ ]:
## What about life in two dimensions? A list of lists is matrix, 
## a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, 
## average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [7]:
# Exercise 1 - refactor the following to use numpy. 
# Use sum_of_b as the variable. 
# **Hint, you'll first need to make sure that the "b" variable 
# is a numpy array**
# sum_of_b = 0
# for row in b:
#     sum_of_b += sum(row)

b = np.array([
    [3, 4, 5],
    [6, 7, 8]
])

In [203]:
sum_of_b = b.sum()
sum_of_b

33

In [200]:
# Exercise 2 - refactor the following to use numpy. 
# min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

In [204]:
min_of_b = b.min()
min_of_b

3

In [206]:
# Exercise 3 - refactor the following maximum calculation to 
# find the answer with numpy.
# max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

max_of_b = b.max()
max_of_b

8

In [207]:
# Exercise 4 - refactor the following using numpy to find the mean of b
# mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

mean_of_b = b.mean()
mean_of_b

5.5

In [211]:
# Exercise 6 - refactor the following to use numpy to find the 
# list of squares 
# squares_of_b = []
# for row in b:
#     for number in row:
#         squares_of_b.append(number**2)

squares_of_b = b**2
squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

In [212]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
# odds_in_b = []
# for row in b:
#     for number in row:
#         if(number % 2 != 0):
#             odds_in_b.append(number)

odds_in_b = b %2 != 0
odds_in_b

array([[ True, False,  True],
       [False,  True, False]])

In [213]:
# Exercise 8 - refactor the following to use numpy to filter only 
#the even numbers
# evens_in_b = []
# for row in b:
#     for number in row:
#         if(number % 2 == 0):
#             evens_in_b.append(number)

evens_in_b = b %2 == 0
evens_in_b

array([[False,  True, False],
       [ True, False,  True]])

In [8]:
# Exercise 9 - print out the shape of the array b.

arr = np.array(b)
print(arr.shape)

(2, 3)


In [15]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. 
# (1 x 6)

reshape = np.array(b).reshape((6))
print(reshape)


[3 4 5 6 7 8]


In [18]:
# Exercise 12 - reshape the array b to be a list of 6 lists, 
# each containing only 1 number (6 x 1)

reshape = np.array(b).reshape((6,1))
print(reshape)

[[3]
 [4]
 [5]
 [6]
 [7]
 [8]]


# Setup 3

In [31]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]


In [23]:
# HINT, you'll first need to make sure that the "c" variable 
# is a numpy array prior to using numpy array methods.

carray = np.array(c)
print(c)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [27]:
# Exercise 1 - Find the min, max, sum, and product of c.

#min
cmin = carray.min()
print(cmin)

#max
cmin = carray.max()
print(cmin)

#sum
cmin = carray.sum()
print(cmin)

#product
cmin = carray.prod()
print(cmin)

1
9
45
362880


In [28]:
# Exercise 2 - Determine the standard deviation of c.
cstd = np.std(carray)
print(cstd)

2.581988897471611


In [32]:
# Exercise 3 - Determine the variance of c.
cvar = np.var(carray)
print(carray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
# Exercise 3 - Determine the variance of c.
cvar = np.var(c)
print(c)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [34]:
# Exercise 4 - Print out the shape of the array c
carr = np.array(carray)
print(carr.shape)

(3, 3)


In [35]:
# Exercise 4 - Print out the shape of the array c
carr = np.array(c)
print(carr.shape)

(3, 3)


In [36]:
# Exercise 5 - Transpose c and print out transposed result.
ctrans = np.transpose(carray)
print(ctrans)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [37]:
# Exercise 5 - Transpose c and print out transposed result.
ctrans = np.transpose(c)
print(ctrans)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [42]:
# Exercise 6 - Get the dot product of the array c with c. 
cdot = np.dot(c,carray)
print(cdot)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [43]:
# Exercise 6 - Get the dot product of the array c with c. 
cdot = np.dot(carray,c)
print(cdot)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [54]:
# Exercise 7 - Write the code necessary to sum up the result of 
# c times c transposed. Answer should be 261 ???

csum = np.transpose(c * ctrans)
print(csum)

[[ 1  8 21]
 [ 8 25 48]
 [21 48 81]]


In [51]:
# Exercise 8 - Write the code necessary to determine the product of 
# c times c transposed. Answer should be 131681894400.
cprod = np.prod(c * ctrans)
print(cprod)

131681894400


# Setup 4

In [62]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

In [66]:
# Exercise 1 - Find the sine of all the numbers in d
dsin = np.sin(d)
print(dsin)

[[ 0.89399666 -0.98803162  0.85090352  0.          0.58061118 -0.80115264]
 [ 0.85090352 -0.89399666  0.98803162 -0.17604595  0.89399666  0.        ]
 [-0.30481062  0.85090352 -0.85090352  0.89399666 -0.85090352 -0.80115264]]


In [67]:
# Exercise 2 - Find the cosine of all the numbers in d
dcos = np.cos(d)
print(dcos)

[[-0.44807362  0.15425145  0.52532199  1.          0.81418097 -0.59846007]
 [ 0.52532199 -0.44807362  0.15425145  0.98438195 -0.44807362  1.        ]
 [-0.95241298  0.52532199  0.52532199 -0.44807362  0.52532199 -0.59846007]]


In [69]:
# Exercise 3 - Find the tangent of all the numbers in d
dtan = np.tan(d)
print(dtan)

[[-1.99520041 -6.4053312   1.61977519  0.          0.71312301  1.33869021]
 [ 1.61977519  1.99520041  6.4053312  -0.17883906 -1.99520041  0.        ]
 [ 0.32004039  1.61977519 -1.61977519 -1.99520041 -1.61977519  1.33869021]]


In [78]:
#finding the array of d
darray = np.array(d)
print(d)

[[90, 30, 45, 0, 120, 180], [45, -90, -30, 270, 90, 0], [60, 45, -45, 90, -45, 180]]


In [80]:
# Exercise 4 - Find all the negative numbers in d
dnegative = darray[darray < 0]
print(dnegative)

[-90 -30 -45 -45]


In [81]:
# Exercise 5 - Find all the positive numbers in d
dpositive = darray[darray > 0]
print(dpositive)

[ 90  30  45 120 180  45 270  90  60  45  90 180]


In [84]:
# Exercise 6 - Return an array of only the unique numbers in d.
uniquenum = np.unique(darray)
print(uniquenum)

[-90 -45 -30   0  30  45  60  90 120 180 270]


In [85]:
# Exercise 7 - Determine how many unique numbers there are in d.
uniquenum = len(np.unique(darray))
print(uniquenum)

11


In [87]:
# Exercise 8 - Print out the shape of d.
dshape = np.array(darray)
print(dshape)

[[ 90  30  45   0 120 180]
 [ 45 -90 -30 270  90   0]
 [ 60  45 -45  90 -45 180]]


In [89]:
# Exercise 9 - Transpose and then print out the shape of d.
dtrans = np.transpose(darray)
print(dtrans)

[[ 90  45  60]
 [ 30 -90  45]
 [ 45 -30 -45]
 [  0 270  90]
 [120  90 -45]
 [180   0 180]]


In [88]:
# Exercise 10 - Reshape d into an array of 9 x 2
dreshape = np.array(darray).reshape((9,2))
print(dreshape)

[[ 90  30]
 [ 45   0]
 [120 180]
 [ 45 -90]
 [-30 270]
 [ 90   0]
 [ 60  45]
 [-45  90]
 [-45 180]]
